google/libultrahdr

fuzzer/ultrahdr_enc_fuzzer.cpp
gainmapmath.cpp
icc.cpp
include/ultrahdr/gainmapmath.h
include/ultrahdr/icc.h
include/ultrahdr/jpegdecoderhelper.h
include/ultrahdr/jpegr.h
jpegdecoderhelper.cpp
jpegencoderhelper.cpp
jpegr.cpp
tests/gainmapmath_test.cpp
tests/jpegr_test.cpp
tests/ultrahdr_app.cpp

Test: Build
Test: ultrahdr_unit_test

ultrahdr: fix compiler warnings

---

tests/ultrahdr_app.cpp

Usage: ultrahdr_app -m 1 -j input.jpg

add support for decode only mode in sample app

---

Android.bp
adobe-hdr-gain-map-license/Android.bp
benchmark/Android.bp
examples/Android.bp
fuzzer/Android.bp
tests/Android.bp

Bug: 313791883
Test: treehugger
Change-Id: I4d97c76ac505774e0308c7e8eed48e127816405c

Enable android build targets

---

CMakeLists.txt
README.md
benchmark/Android.bp
benchmark/benchmark_test.cpp
examples/Android.bp
examples/ultrahdr_app.cpp

Change-Id: I972856d603782d3167f7d002896ce87161292d96

Add benchmark tests for encoder apis

---

lib/src/jpegrutils.cpp

libimage_io fails to handle xmp packet header and trailer. Before handing the data to lib strip these fields
fixes google#54

handle xmp packet Header and Trailer during parsing

---

lib/src/jpegr.cpp

Change-Id: Id28c66918750dc65dab2865dcb04b2f697ff9735

validate input gamut info for encode api-2 and api-3

---

lib/include/ultrahdr/ultrahdrcommon.h
lib/src/ultrahdr_api.cpp
ultrahdr_api.h

Add util functions of decoder

---

examples/ultrahdr_app.cpp

Test: ./ultrahdr_app -m 0 -p cosmat_1920x1080_p010.yuv \
-w 1920 -h 1080 -q 97

Fix possible leaks in sample app

---

examples/metadata.cfg
examples/ultrahdr_app.cpp

fixes #71
Test: ultrahdr_app -m 0 -i cosmat_1920x1080_420_8bit.jpg \ -g cosmat_1920x1080_420_8bit.jpg -f metadata.cfg

Add support for API-4 in sample app

---

CMakeLists.txt
lib/src/jpegdecoderhelper.cpp
lib/src/jpegr.cpp

For deps, use pre-installed packages if available

---

lib/include/ultrahdr/ultrahdrcommon.h
lib/src/ultrahdr_api.cpp

@Thanks Dichen.
Change-Id: I4d42d152db2d1c0ddbaf797505fb117d61c8d1be

Improved argument error checking for apis

---

.github/workflows/cmake.yml

Update Cmake.yml to test few more combinations by enable dependency builds.

Add more targets to cmake.yml

---

CMakeLists.txt
README.md
fuzzer/README.md
libuhdr.pc.template

- restrict install and uninstall targets to Un*x
- improvements in cmakelists.txt and pc template (thanks to milos)
- Fixes #95
- Updates to readme.md
Test: make install

improve ce9d00b

---

lib/src/ultrahdr_api.cpp

Improve error checks during parameter validation

---

lib/include/ultrahdr/gainmapmath.h
lib/include/ultrahdr/jpegr.h
lib/src/gainmapmath.cpp
lib/src/jpegr.cpp

fix windows builds and clang-format changes

---

ultrahdr_api.h

Test: Build
Change-Id: I117ce7a4e0f950f714e64b2cd0ab395d7ac32332

Add missing modifier to uhdr api interface function

---

lib/include/ultrahdr/editorhelper.h
lib/src/editorhelper.cpp
lib/src/ultrahdr_api.cpp
tests/Android.bp
tests/editorhelper_test.cpp

Change-Id: I293726f4bf765987a77db1d06560f864bacb4aa9

refactor editor helper for adding arch specific impl

---

.github/workflows/cmake.yml
CMakeLists.txt
README.md

- updated pre-requistes and side effects
- add support for building shared, static targets (selective)
- improve documentation in cmakelists
- update readme.md

Improve cmakelists.txt

---

CMakeLists.txt
ultrahdr_api.h

export uhdr lib interface symbols correctly in apple builds

---

lib/src/editorhelper.cpp
lib/src/gainmapmath.cpp
lib/src/ultrahdr_api.cpp

fix warnings due to flag -Wpessimizing-move

---

CMakeLists.txt
lib/include/ultrahdr/gainmapmath.h
lib/include/ultrahdr/jpegrutils.h
lib/src/gainmapmath.cpp
lib/src/jpegdecoderhelper.cpp
lib/src/jpegr.cpp
lib/src/jpegrutils.cpp
lib/src/ultrahdr_api.cpp

fix compilation warnings for flags -Wall, -Wextra, -Wshadow

---

Android.bp
CMakeLists.txt
lib/include/ultrahdr/editorhelper.h
lib/include/ultrahdr/ultrahdrcommon.h
lib/src/dsp/arm/editorhelper_neon.cpp
lib/src/editorhelper.cpp

Change-Id: I4d42d152db2d1c0ddbaf797505fb117d52c7d2bf

Add neon intrinsics for editor helper utils

---

examples/ultrahdr_app.cpp

Sample app returns with out releasing resources during read failure. This is addressed.
Test: ./ultrahdr_app -m 0 -p input.yuv -w 64 -h 64

fix leaks in sample app during error scenarios

---

lib/src/ultrahdr_api.cpp
tests/jpegr_test.cpp

Add error checks for color range field

---

lib/include/ultrahdr/gainmapmath.h
lib/src/gainmapmath.cpp
lib/src/jpegr.cpp
tests/gainmapmath_test.cpp

Refactoring, move reusable code to common

---

lib/include/ultrahdr/gainmapmath.h
lib/src/gainmapmath.cpp

Bug: 349653994
Change-Id: I1554a518aade2d0a98a20c9c0e5dc3974673ec1c

Refactor vector creation with a single generalized function

---

examples/ultrahdr_app.cpp

update sample application usage

---

lib/include/ultrahdr/jpegr.h

fix data type of gamma getter/setter function

---

fuzzer/ultrahdr_dec_fuzzer.cpp
fuzzer/ultrahdr_enc_fuzzer.cpp

Test: ./ultrahdr_dec_fuzzer
Change-Id: I1554a518aade2d0a98a20c9c0e5dc3973664ec2c

Update fuzzers for better code coverage

---

lib/src/ultrahdr_api.cpp

encoder apis [2-4] accept compressed sdr intent as an argument. Validate this arg in depth.
Briefly,
1. return error if the input has no valid jpeg
2. pick first if the input has multiple jpeg images
fixes #166

Improve encoder input argument validation

---

lib/src/ultrahdr_api.cpp
ultrahdr_api.h

API: change a parameter type from bool to int

---

README.md
cmake/libuhdr.pc.in
examples/ultrahdr_app.cpp
lib/include/ultrahdr/jpegr.h
lib/src/jpegr.cpp

If opengl is enabled, then add egl and glesv3 libraries in to Libs.Private list for static linking
also minor documentation updates in sample app and clang-formatting
Test: Build

update pkg-config file with opengles dependencies

---

lib/include/ultrahdr/editorhelper.h
lib/include/ultrahdr/ultrahdrcommon.h
lib/src/editorhelper.cpp
lib/src/gpu/applygainmap_gl.cpp
lib/src/gpu/editorhelper_gl.cpp
lib/src/gpu/uhdr_gl_utils.cpp
lib/src/jpegr.cpp
lib/src/ultrahdr_api.cpp
tests/editorhelper_test.cpp

Change-Id: Ifb4ada9156863bdbd3c5de54a07a1a4cdb1e2fb8

Add gpu acceleration support for editor helper functions

---

CMakeLists.txt
ultrahdr_api.h

Update documentation of api interface

---

lib/src/icc.cpp

while parsing iccHeader the base adress of icc data is casted to a type that does not match the alignment requirements of the type it is being casted to. In this scenario, copy icc data to aligned address and continue parsing

ubsan: fix misaligned address load

---

lib/include/ultrahdr/gainmapmath.h
lib/src/gainmapmath.cpp

Minor optimization, saves few CPU cycles

Do not apply gamma correction if gamma is 1.0

---

lib/include/ultrahdr/ultrahdrcommon.h
lib/src/jpegencoderhelper.cpp

Not really important. But useful notes for debugging

Insert comment marker for gainmap image

---

lib/src/jpegdecoderhelper.cpp

fix lazy checking during subsample format determination

---

.github/workflows/cmake_linux.yml
examples/ultrahdr_app.cpp
fuzzer/ultrahdr_dec_fuzzer.cpp
lib/include/ultrahdr/ultrahdrcommon.h
lib/src/jpegencoderhelper.cpp
lib/src/ultrahdr_api.cpp
ultrahdr_api.h

Also,
- fixed few api names for consistency.
- moved lib version macro to public interface
- documented version semantics inconsistencies

Add apis to access primary and gainmap compressed data

---

fuzzer/ossfuzz.sh
fuzzer/ultrahdr_dec_fuzzer.cpp
fuzzer/ultrahdr_enc_fuzzer.cpp

update fuzzers for improved coverage

---

fuzzer/ultrahdr_dec_fuzzer.cpp
fuzzer/ultrahdr_enc_fuzzer.cpp

crop, resize, mirror and rotate are added to encoder and decoder fuzzer tests.
Test: ./ultrahdr_dec_fuzzer

fuzzers: add editor effects api to fuzz tests

---

lib/include/ultrahdr/jpegr.h

Change-Id: I34c515da63d97b334abdcaebb0eea23fed06667f

Make tonemapping and gainmap generation public

---

examples/ultrahdr_app.cpp
java/UltraHdrApp.java
java/com/google/media/codecs/ultrahdr/UltraHDREncoder.java
java/jni/com_google_media_codecs_ultrahdr_UltraHDREncoder.h
java/jni/ultrahdr-jni.cpp
lib/include/ultrahdr/gainmapmath.h
lib/include/ultrahdr/jpegr.h
lib/include/ultrahdr/ultrahdrcommon.h
lib/src/gainmapmath.cpp
lib/src/jpegr.cpp
lib/src/ultrahdr_api.cpp
ultrahdr_api.h

add API to set mastering display, target display peak brightness

add API to set mastering display, target display peak brightness

---

lib/include/ultrahdr/gainmapmath.h
lib/include/ultrahdr/ultrahdrcommon.h
lib/src/gainmapmath.cpp
lib/src/gpu/applygainmap_gl.cpp
lib/src/jpegr.cpp
lib/src/ultrahdr_api.cpp
tests/gainmapmath_test.cpp

- validate gainmap metadata during decoding before using it
- fix issues in gainmap weight factor computation during applyGainMap

corrections in gainmap weight factor computation

---

CMakeLists.txt
DESCRIPTION
cmake/package.cmake
docs/building.md

Test: cmake -G Ninja ../ && ninja && ninja package

add support for generating packages using cpack

---

lib/src/ultrahdr_api.cpp

Fixed out-of-bounds memory access during image resizing caused by integer overflow when computing image dimensions. The fix involves explicitly casting operands to size_t to ensure correct size calculations, particularly for large image dimensions.
fixes oss-fuzz-375766880
Test: ./ultrahdr_dec_fuzzer <clusterfuzz-vector>
Change-Id: Icf3e5c614c20925c3570d44cda43bc6a3ac01ef7

Fix oob access while resizing an image

---

lib/include/ultrahdr/gainmapmath.h
lib/src/gainmapmath.cpp
lib/src/gpu/applygainmap_gl.cpp
lib/src/jpegr.cpp
tests/gainmapmath_test.cpp

add support for decoding images with non-zero hdr/sdr offsets

---

fuzzer/ultrahdr_enc_fuzzer.cpp

update enc fuzzer for half fp inputs

---

lib/include/ultrahdr/gainmapmetadata.h
lib/src/gainmapmetadata.cpp
lib/src/jpegr.cpp
tests/gainmapmetadata_test.cpp

improve iso support
