.github/workflows/cmake.yml

cmake configure step was wrongly hard-coded to clang which prevented testing the gcc based builds. 
It is now updated to pick appropriate compilers based on the build type.

cmake.yml: Test cmake builds using gcc

---

.github/workflows/cmake.yml
CMakeLists.txt
fuzzer/README.md

Fuzzer build is now based on an argument passed to cmake. 
With this, macos builds can now be verified for each pull request.

cmake: Pass -DENABLE_FUZZERS=ON to enable building fuzzers

---

CMakeLists.txt

When using some older compilers, the missing pthread dependency results in build errors.

cmake: Add pthread dependendency

---

jpegdecoderhelper.cpp
jpegr.cpp

- Override output_message method for jpeg decoder
- Use SetMessageWriter() while calling Jpeg scanner from image_io
This ensures that logs are written using ALOG routines and can be suppressed for fuzzer runs easily.

Use ALOG methods to print messages from jpeg and image_io

---

CMakeLists.txt

- Build only jpeg-static
- Add variables for libjpeg-turbo and gtest includes and libraries
- add dependencies on libjpeg-turbo and gtest to ensure they are built first before building the app, unit test and fuzzers

cmake updates

---

CMakeLists.txt
third_party/cmake/image_io/CMakeLists.txt

Current CMakeLists.txt prevented cross compiling from x86_64 machine for an x86 target.

cmake: Fix 32-bit cross compilation

---

jpegencoderhelper.cpp

jpeg_write_raw_data() expects input size to be aligned to MCU. If the image dimensions are not aligned then padding is done for boundary rows. The padded rows allocation is not proper and this is corrected.
Bug: oss-fuzz-63314
Test: ultrahdr_enc_fuzzer

Allocate width aligned to MCU size for boundary rows

---

jpegdecoderhelper.cpp
jpegencoderhelper.cpp

If luma stride is aligned and chroma stride is not aligned to mcu row, jpeg_write_raw_data() is using unaligned chroma pointers during processing. This should cause oob reads. This is fixed.
Allocate memory for alignment regions only when necessary.
After decompress, dont copy decoded rows that are outside image boundaries.

rework jpeg encoder and decoder helper utils

---

CMakeLists.txt

add_dependencies() calls are needed to ensure that cmake builds work as expected when running multiple compile jobs in parallel.

CMakeLists.txt: Add missing add_dependencies

---

CMakeLists.txt

cflags, cxxflags, sanitize flags as of now are applied only to current project. Extend these to its dependencies as well
ensure clean target, cleans dependencies as well

Apply current project compilation flags to external projects

---

lib/src/icc.cpp

Bug: 317782344
Test: ultrahdr_app -m 1 -j ./poc

Perform boundary checks before parsing iccData

---

lib/src/gainmapmath.cpp
tests/gainmapmath_test.cpp

Replaces the divides in the aforementioned functions with reciprocal multiplies. This change requires modification of the test functions as well, otherwise the results end up off by one.
This improves performance across the board with the improvement most notable on small in-order Arm cores. This benefit should be amplified by subsequent Neon optimizations.

Replace divides with multiplies in get*Pixel functions

---

examples/ultrahdr_app.cpp
lib/src/ultrahdr_api.cpp
tests/jpegr_test.cpp

CleanUp: Use enum constant instead of integer literals during access

---

lib/src/jpegr.cpp

If a valid jpeg image with no gainmap image is fed as input, the function is ignoring the error received and parse unassigned gainmap image structure causing seg fault

Fix issue in getJPEGRInfo()

---

fuzzer/ultrahdr_dec_fuzzer.cpp
fuzzer/ultrahdr_enc_fuzzer.cpp

Earlier the gainmap data is allocated by the library and shared externally. Now the decodeJPEGR function expects to receive the location to which the gainmap data needs to be written

Update fuzzer according to the updates made to decodeJPEGR

---

CMakeLists.txt

mkdir build && cd build
emcmake cmake ../
cmake --build ./
Successfully builds all targets with Emscripten toolchain. But, currently no bindings are present to really make use of the libraries that were built.
fixes #60

Enable wasm build

---

Android.bp

Made the following changes in Android.bp
- Added editorhelper.cpp
- rtti: true because library now uses dynamic_cast

Update Android.bp for recent changes

---

examples/ultrahdr_app.cpp

Test: ultrahdr_app -m 0 -p cosmat_1920x1080_p010.yuv \
-w 1920 -h 1080 -q 97

fix incorrect bias for chroma planes in sample app

---

CMakeLists.txt

In 4a46a1cb4a5f7105674402fd50fb53e3ab01cffb, CMakeLists.txt was unintentionally modified to select only editor helper tests. This is now fixed by re-enabling all the tests in tests directory.

cmake: Re-enable building all the tests

---

lib/include/ultrahdr/gainmapmath.h
lib/src/gainmapmath.cpp
lib/src/jpegr.cpp
tests/gainmapmath_test.cpp

Update transformYuv420 function interface in preparation for adding a (Neon) SIMD implementation:
* Move double for-loops used for interating over the image buffer from JpegR::convertYuv into the transformYuv420.
* Use an array of coefficients instead of passing a function pointer for the required conversion.
Also replace the color gamut conversion functions with a generic implementation and update the test-suite accordingly.
Change-Id: Ia50a18e01cdcdfefd0e1446a1720a758ab7e5a9d

Update transformYuv420/convertYuv interface

---

examples/ultrahdr_app.cpp
lib/include/ultrahdr/gainmapmath.h
lib/src/editorhelper.cpp
lib/src/gainmapmath.cpp
lib/src/ultrahdr_api.cpp

Fixed issues in color space conversion modules of
sample app. Also rename variables in sample app
accurately
Test: ultrahdr_app -m 0 -p cosmat_1920x1080_p010.yuv \
-w 1920 -h 1080 -q 97 -a 0
Change-Id: I86eeef02f5bc0e6b8c28de0da46b0f6d7eec6358

Add support for rgb formats during encode

---

lib/src/editorhelper.cpp
lib/src/ultrahdr_api.cpp

- add mirror, rotate, crop, resize effects in encode path. This change does not enable effects completely as there are no api calls advertised to invoke the effects
- improve error logging
Test: Manual

add support for simple edit effects in encode path

---

lib/src/gainmapmetadata.cpp

subtraction between unsigned types results in large values due to wrap around behavior. This is allowing out of bound access. This is corrected
oss-fuzz: 68933
Test: ultrahdr_dec_fuzzer fuzzvec

fix oob access in decodeGainmapMetadata()

---

ultrahdr_api.h

Referencing uhdr_decode() instead of uhdr_decompress()

Corrected comment referencing incorrect function name

---

examples/ultrahdr_app.cpp
lib/include/ultrahdr/jpegdecoderhelper.h
lib/include/ultrahdr/jpegrutils.h
lib/src/jpegdecoderhelper.cpp
lib/src/jpegr.cpp
lib/src/jpegrutils.cpp
tests/jpegdecoderhelper_test.cpp

Initial versions supports decoding images with subsampling factor 4:2:0. This changes broadens the support.
Test: ./ultrahdr_dec_fuzzer

Add support for decoding different jpg subsampling factors

---

fuzzer/ultrahdr_enc_fuzzer.cpp
lib/include/ultrahdr/jpegencoderhelper.h
lib/src/jpegencoderhelper.cpp
lib/src/jpegr.cpp
tests/jpegencoderhelper_test.cpp

- Add support for more sampling formats
- RGB jpeg encode now defaults to 444 sampling format instead of 420
- For unaligned blocks memset chroma planes to 128 to create black borders
- Add more fail safe checks, diagnostics
- Ensure memory is released during encoding failures

Updates to jpeg encoder helper class

---

Android.bp
lib/src/jpegr.cpp

This is working towards supporting a Windows build of libandroid_runtime.
Bug: 340885449
Test: build libultrahdr for Windows

Enable Windows build for libultrahdr

---

examples/ultrahdr_app.cpp
fuzzer/ultrahdr_enc_fuzzer.cpp
lib/include/ultrahdr/jpegdecoderhelper.h
lib/include/ultrahdr/jpegencoderhelper.h
lib/include/ultrahdr/jpegr.h
lib/include/ultrahdr/ultrahdr.h
lib/src/jpegdecoderhelper.cpp
lib/src/jpegencoderhelper.cpp
lib/src/jpegr.cpp
lib/src/ultrahdr_api.cpp
tests/jpegencoderhelper_test.cpp
tests/jpegr_test.cpp
ultrahdr_api.h

ultrahdr_api.h, ultrahdr.h, jpegdecoderhelper.h, jpegencoderhelper.h are maintaining different enum classes for pixel formats local to their modules. All these are unified.

unify pixel format enumerations across utils

---

lib/include/ultrahdr/gainmapmath.h
lib/src/dsp/arm/gainmapmath_neon.cpp
lib/src/jpegr.cpp
tests/gainmapmath_test.cpp

These 2 patches add a Arm Neon version for the YUV color gamut conversion as well as the transformYuv420 function.

Yuv color gamut conversion and transformYuv420 using Arm Neon.

---

lib/include/ultrahdr/jpegencoderhelper.h
lib/src/jpegencoderhelper.cpp
lib/src/jpegr.cpp
tests/jpegencoderhelper_test.cpp

everywhere in the library stride is communicated in units of pixels. But during multi channel gainmap compression this is signalled in bytes. This is corrected.

Signal stride in pixel denomination and not bytes

---

lib/src/ultrahdr_api.cpp
ultrahdr_api.h

Commit 073d5c7580072c246e3d6f34eee2a9200b0d0d4e added the function `uhdr_enc_set_using_multi_channel_gainmap()` to the public API, which used a `bool` type in one of its parameters.
[But `bool` is a keyword only since C23](https://en.cppreference.com/w/c/keyword/bool). Before C23, `bool` is defined in the header `<stdbool.h>`, and this header is missing from the mentioned commit. Client applications that are not compiling in C23 (or later) mode will encounter an error when including the `<ultrahdr_api.h>` header, saying that `bool` is an unknown type.
For example, compiling ImageMagick with ultrahdr support gives the following error:
```
In file included from coders/uhdr.c:47:
/usr/include/ultrahdr_api.h:320:72: error: unknown type name 'bool'
320 | …
```

API: change a parameter type from bool to int

---

benchmark/benchmark_test.cpp
examples/ultrahdr_app.cpp
fuzzer/ultrahdr_enc_fuzzer.cpp
lib/include/ultrahdr/gainmapmath.h
lib/include/ultrahdr/gainmapmetadata.h
lib/include/ultrahdr/icc.h
lib/include/ultrahdr/jpegdecoderhelper.h
lib/include/ultrahdr/jpegencoderhelper.h
lib/include/ultrahdr/jpegr.h
lib/include/ultrahdr/jpegrutils.h
lib/include/ultrahdr/multipictureformat.h
lib/include/ultrahdr/ultrahdr.h
lib/include/ultrahdr/ultrahdrcommon.h
lib/src/dsp/arm/gainmapmath_neon.cpp
lib/src/gainmapmath.cpp
lib/src/gainmapmetadata.cpp
lib/src/icc.cpp
lib/src/jpegdecoderhelper.cpp
lib/src/jpegencoderhelper.cpp
lib/src/jpegr.cpp
lib/src/jpegrutils.cpp
lib/src/ultrahdr_api.cpp
tests/gainmapmath_test.cpp
tests/gainmapmetadata_test.cpp
tests/icchelper_test.cpp
tests/jpegdecoderhelper_test.cpp
tests/jpegencoderhelper_test.cpp
tests/jpegr_test.cpp
ultrahdr_api.h

This is a major change but maintains bitexactness with previous commit. This change unifies legacy structure definitions with definitions of ultrahdr_api.h. This helps for better extensibility for new features and avoid redundancy.
Legacy structures are moved to ultrahdr.h. These are deprecated and only retained for backward compatibility.
Briefly,
- unify ultrahdr_color_gamut with uhdr_color_gamut_t
- unify ultrahdr_transfer_function with uhdr_color_transfer_t
- unify ultrahdr_metadata_struct with uhdr_gainmap_metadata_t
- unify jpegr_uncompressed_struct with uhdr_raw_image_t
- unify jpegr_compressed_struct with uhdr_compressed_image_t
- unify jpegr_exif_struct with uhdr_mem_block_t
- unify status_t with uhdr_error_info_t
- Deprecate ultrahdr_output_format
- Added methods to Jpeg*Helper …

Update library to use definitions of ultrahdr_api everywhere

---

lib/include/ultrahdr/gainmapmath.h
lib/src/gainmapmath.cpp
lib/src/jpegdecoderhelper.cpp
lib/src/jpegr.cpp

- Update generateGainMap and applyRecMap to support sdr intent with sampling formats 444, 422.
This change does not enable 444, 422 support completely as hdr intents currently support only p010. More changes are required towards enabling 444, 422 support completely.
Fixes #69
Test: ultrahdr_app.exe -m 0 -p trin_rain_converted_using_ffmpeg.yuv -a 0 \ -i trin_rain_base_sdr_high_quality.jpeg -c 1 -w 1080 -h 1350

Updates towards 4ab sub-sampling format support

---

lib/src/dsp/arm/gainmapmath_neon.cpp

Fixes two issues:
-  gcc `__attribute__` keyword not supported by MSVC
- assert looking for `width` variable instead of `w`

Fixed compiling ARM64 target for Windows

---

lib/include/ultrahdr/jpegr.h
lib/src/jpegr.cpp

For encode API-0 when an internal tone map algorithm is used, luma needs to be calculated as max {r, g, b} because this will ensure that r, g, b ratios be preserved

Fix color hue shifting for encode API-0

---

lib/src/gainmapmath.cpp

The output of gamut conversion is observed to produce values that are outside limits [0.0f - 1.0f]. Before accessing these values limit the same.

clamp output of gamut conversion to limit bounds

---

lib/src/gainmapmath.cpp
tests/gainmapmath_test.cpp

The output of applyRecMap while converting to int, ensure a round factor is added for small error representation

Add round factor during float to int conversion

---

Android.bp
lib/src/jpegr.cpp

The issues that were seen earlier when compiling convertYuv_neon in 32 bit build are now fixed.

Enable convertYuv_neon in 32bit builds

---

lib/include/ultrahdr/jpegr.h
lib/include/ultrahdr/ultrahdrcommon.h
lib/src/jpegr.cpp
lib/src/ultrahdr_api.cpp

uhdr_dec_probe() parses gainmap metadata present in xmp block only. If iso block contains gainmap metadata this is not handled. Add support for same.
Test:./ultrahdr_unit_test

add support for iso metadata parsing in probe path

---

lib/include/ultrahdr/ultrahdrcommon.h
lib/src/ultrahdr_api.cpp

Current implementation is overwriting fields reserved for api-4 support. An accidental call to uhdr_enc_set_gainmap_image followed by uhdr_enc_set_gainmap_gamma can cause problems in the encoded image.
Also default initialize the gamma field to 1.0

use separate field to store configured gainmap gamma

---

lib/include/ultrahdr/gainmapmath.h
lib/src/dsp/arm/gainmapmath_neon.cpp
lib/src/editorhelper.cpp
lib/src/gainmapmath.cpp
lib/src/jpegr.cpp
lib/src/ultrahdr_api.cpp
ultrahdr_api.h

Only encode api variant 3 has support for subsampling format 1x1. Extend this support for encode api variants 0 to 2.
fixes #202

Add support for 444 subsampling format in uhdr encoder

---

lib/src/gainmapmath.cpp

applyGain() of uhdr_decode for multichannel gainmap images are not performing gamma correction. This is fixed.

Apply gamma correction while decoding multichannel gainmaps

---

lib/include/ultrahdr/ultrahdrcommon.h
lib/src/ultrahdr_api.cpp

Once the encode/decode operation is underway, it is possible for the client to modify the list of effects to apply. Restrict effects configuration during init phase only.

Do not allow effects to be configured in running state

---

lib/src/gainmapmath.cpp

Some constants used in inverse oetf functions of sRGB and PQ are not accurate. These are fixed.

Correct inverse oetf functions of sRGB and PQ

---

lib/src/ultrahdr_api.cpp

For raw intents with color format rgb1010102 and rgba8888, the input fields are not validated correctly. This is addressed.

Add missing validation checks for raw intents

---

fuzzer/ultrahdr_enc_fuzzer.cpp
lib/src/jpegr.cpp
lib/src/ultrahdr_api.cpp

very large gainmap scale factors result in large heap requirements during ShepardsIDW instantiation. As large downsample factors are not beneficial from quality stand point and also for embedded devices profile point of view, add an upper bound to the config
fixes oss-fuzz:	70927

Add upper limit to gainmap scale factor

---

lib/src/jpegr.cpp

gainmap image was wrongly being initialized with jpeg images data in API-4.

Fix gainmap initializations in API-4 encoding

---

fuzzer/ossfuzz.sh

Shift sanitizer flags a few failures that prevent further fuzzing with other undefined behavior sanitizers enabled.
Disable shift sanitizer till the library is updated to avoid these undefined shift sanitizer issues.

ossfuzz.sh: Opt out of shift sanitizer

---

CMakeLists.txt

If planned to add to major Linux distros, the shared library should be versioned, i.e. as described in [Debian policy](https://www.debian.org/doc/debian-policy/ch-sharedlibs#s-sharedlibs-runtime).
```shell
$ tree
.
├── include
│   └── ultrahdr_api.h
└── lib
├── libuhdr.so -> libuhdr.so.1
├── libuhdr.so.1 -> libuhdr.so.1.0
├── libuhdr.so.1.0
└── pkgconfig
└── libuhdr.pc
```

cmake: add version to the shared library

---

examples/ultrahdr_app.cpp
fuzzer/ultrahdr_enc_fuzzer.cpp
lib/include/ultrahdr/gainmapmath.h
lib/include/ultrahdr/jpegr.h
lib/include/ultrahdr/ultrahdrcommon.h
lib/src/gainmapmath.cpp
lib/src/jpegr.cpp
lib/src/ultrahdr_api.cpp
tests/gainmapmath_test.cpp
ultrahdr_api.h

Current implementation clips min/max content boost to a smaller range. Allow for larger excursions for better hdr intent representation.
Also, fixed round factor before encoding gainmap coefficient

Allow for larger excursions of min, max content boost

---

examples/ultrahdr_app.cpp
lib/include/ultrahdr/jpegr.h
lib/include/ultrahdr/ultrahdrcommon.h
lib/src/jpegr.cpp
lib/src/ultrahdr_api.cpp
ultrahdr_api.h

The min/max content boost for different encoding presets are computed internally basing on the input hdr and sdr intents. This change introduces an API to configure the values from the app side. If the library during its computations observes a small min-max range, then client recommendation is ignored. Otherwise, the configured values are selected.
fixes #160
Test: ./ultrahdr_app <options> -k 0.01 -K 8.0

add support for configuring min/max content boost

---

CMakeLists.txt
lib/include/ultrahdr/gainmapmath.h
lib/src/gainmapmath.cpp
lib/src/gpu/applygainmap_gl.cpp
lib/src/gpu/uhdr_gl_utils.cpp
lib/src/jpegr.cpp
lib/src/ultrahdr_api.cpp

For rgb inputs, these are first converted to ycbcr inputs and stored internally. During gainmap generation, these are again converted back to rgb. These redundant color space conversions are removed.
fixed few compilation warnings

Improve rgb input handling

---

CMakeLists.txt

By default BUILD_SHARED_LIBS is enabled. In this mode, shared libuhdr and static libuhdr are generated in the build process. These libraries, header file and pkg-config file are installed in the default/desired location after `make install`.
To make use of this,
g++ ultrahdr_app.cpp `pkg-config --libs libuhdr`
This is expected to generate a dynamic executable.
For static linking,
g++ --static ultrahdr_app.cpp `pkg-config --static --libs libuhdr`
This is expected to generate a static executable. However, this can also fail if the static version of the dependencies are not available. For instance, if the library is built with GPU acceleration enabled, then mostly static versions of EGL and GLESv3 may not be present causing the aforth mentioned command to fail. In this scenario, we have to …

Add support for installing static library

---

lib/src/jpegr.cpp

In encoding scenario - 2, the API receives hdr intent, sdr intent and sdr intent compressed. It is expected that sdr intent and sdr intent compressed are related via encode-decode process. As there is no validation for this assumption, some sdr intent and a different compressed image can be configured, resulting in some uhdr image. This change introduces a simple error check to avoid accidental mis-configurations.

Improve error checking for encoding scenario - 2

---

lib/src/gainmapmetadata.cpp
third_party/image_io/src/jpeg/jpeg_xmp_info.cc

Not all compilers are reporting these warnings. These are false positives. Fixing them anyways.

fix build warnings

---

CMakeLists.txt

In generator expression $<TARGET_OBJECTS:objLib>, objLib must be an object of type OBJECT_LIBRARY. This is relaxed in version 15.
https://cmake.org/cmake/help/v3.13/manual/cmake-generator-expressions.7.html https://cmake.org/cmake/help/v3.15/manual/cmake-generator-expressions.7.html
Test: Build

Correct cmake minimum version required.

---

CMakeLists.txt

In android builds, log library is used for verbose. The build process searches for the availability of the library. But the result of search is not properly used. This is addressed.
Test: Build

check result of find_library() before progressing

---

lib/include/ultrahdr/ultrahdrcommon.h
lib/src/editorhelper.cpp
lib/src/gpu/applygainmap_gl.cpp
lib/src/gpu/uhdr_gl_utils.cpp
lib/src/ultrahdr_api.cpp

After applyGainMap, the frame buffers are copied to CPU. If image editing effects are to be applied, these are again copied to GPU. This consumes time and can be avoided. The current change defers GPU to CPU transfer to the end after all GL processing is done.
Test: ./ultrahdr_app -m 1 -j input_uhdr.jpg -o 1 -O 5
Change-Id: I9b3e401027ab9d44e2c6aeb664fb10aee2496b52

Reuse applyGainMap GL textures if effects are to be applied

---

fuzzer/ultrahdr_enc_fuzzer.cpp
lib/src/jpegencoderhelper.cpp
lib/src/ultrahdr_api.cpp

The library supports input color formats UHDR_IMG_FMT_24bppYCbCrP010, UHDR_IMG_FMT_12bppYCbCr420. Both these formats have chroma planes subsampled by 2, horizontally and vertically. Each chroma pixel corresponds to 4 luma pixels. Library holds this attribute too tightly and evaluates chroma plane dimensions as half of luma plane dimensions (round_down(w / 2) and round_down(h/2)). It is possible to have 420 subsampled images with odd dimensions where the edge chroma pixels correspond to 1 or 2 luma pixels but this was not handled. For rgb inputs, this restriction need not be enforced. The current change lifts this gating.

enable support for odd dimensions for rgb inputs

---

CMakeLists.txt
examples/ultrahdr_app.cpp
java/com/google/media/codecs/ultrahdr/UltraHDREncoder.java
lib/include/ultrahdr/jpegr.h
lib/src/gainmapmetadata.cpp
lib/src/ultrahdr_api.cpp
tests/jpegr_test.cpp
ultrahdr_api.h

By default gainmap scale factor is set to 1, multi-channel gainmap encoding is enabled.

Modify few default encoding configurations

---

.github/workflows/cmake_android.yml
java/UltraHdrApp.java
java/com/google/media/codecs/ultrahdr/UltraHDRDecoder.java
java/jni/com_google_media_codecs_ultrahdr_UltraHDRDecoder.h
java/jni/ultrahdr-jni.cpp

commit d1ab30c has made changes to ultrahdr_api.h. This is causing issues during jni build. This is addressed.
add java interface for newly added decoder api

fix build issues seen with option UHDR_BUILD_JAVA=1

---

docs/building.md

There might be some corrections in `dosc/build.md`.
* MSYS2 and MSys are [not the same project](https://www.msys2.org/wiki/MSYS2-introduction/), and calling it "MSYS" might be misleading for some Windows users who are not familiar with these softwares.
> It is an **independent rewrite of MSys**, based on modern Cygwin (POSIX compatibility layer) and MinGW-w64 with the aim of better interoperability with native Windows software.
* MSYS2 now [defaults to `ucrt64`](https://www.msys2.org/news/#2022-10-29-changing-the-default-environment-from-mingw64-to-ucrt64) which has better support with modern C, see also [MSYS2's environments](https://www.msys2.org/docs/environments/#msvcrt-vs-ucrt). So we may follow them to recommend to build in `ucrt64` environment.

Fix doc of windows platform build with MSYS2

---

docs/building.md
fuzzer/ossfuzz.sh
lib/include/ultrahdr/gainmapmath.h
lib/include/ultrahdr/ultrahdrcommon.h

commit ea72bc8 opts uhdr library out of shift sanitizer validation. This was because function floatToHalf was raising errors. This change re-enables shift sanitizer by excluding floatToHalf from being sanitized. A more elegant solution to the problem fixed by ea72bc8.
Fixing floatToHalf() to not raise ubsan errors is the correct and permanent fix. Until then, this should help continue fuzzing.

ossfuzz.sh: re-enable shift sanitizer

---

lib/src/jpegr.cpp

if gainmap image is larger than base image then gainmap scale factor computes to < 1. Integral representation of this variable is used during job enqueue. The same job gets repeatedly enqueued as the loop counter increment is now zero. This is addressed.
fixes #oss-fuzz-42537374
Test: ./ultrahdr_dec_fuzzer <clusterfuzz-dec-vector>

fix hang if gainmap image is larger than base image

---

lib/src/gainmapmetadata.cpp
lib/src/ultrahdr_api.cpp

Also, added additional guard checks for float inputs
fixes oss-fuzz-369652657
Test: ./ultrahdr_enc_fuzzer <cluster-fuzz-test-vector>

Dont discard return values from func floatToUnsignedFraction

---

lib/src/jpegencoderhelper.cpp

Some impls of jpeg, does not recognize booleans 'true' and 'false'. They maintain internal macros 'TRUE' and 'FALSE'. Use them instead for universal portability.
Test: Build

Use TRUE instead of true

---

lib/include/ultrahdr/editorhelper.h
lib/src/editorhelper.cpp
lib/src/gpu/editorhelper_gl.cpp
lib/src/ultrahdr_api.cpp
tests/editorhelper_test.cpp

previous crop implementation involved pointer manipulation. That is base address of plane buffers are offseted by `top * stride + left`. While encoding these buffers, due to alignment requirements of jpeg_write_raw_data, during last MCU row oob access is seen. This change modifies the crop implementation from in-place to new alloc + copy and resolves the oob access issue.
fixes oss-fuzz-371659888
Test: ./ultrahdr_enc_fuzzer <clusterfuzz-vector>
Change-Id: Icf3e5c614c20925c3570d44cda43bc6a3ac02ef3

fix oob access while encoding image edited with crop effect

---

lib/include/ultrahdr/editorhelper.h
lib/include/ultrahdr/gainmapmath.h
lib/src/editorhelper.cpp
lib/src/gainmapmath.cpp
lib/src/jpegr.cpp

If the aspect ratio of the gainmap image differs from the primary image, the library throws an error. Try resizing the gainmap image to primary image dimensions before returning with error.

use resize filter during applyGainMap process

---

lib/include/ultrahdr/gainmapmath.h
lib/src/dsp/arm/gainmapmath_neon.cpp
lib/src/jpegr.cpp

This change implements a neon equivalent of
convert_raw_input_to_ycbcr(). However not all combinations are handled. Only rgba888 to yuv444 conversion is supported as it happens to be the most common use case.
Test: ./ultrahdr_app <options>

add rgba8888 to yuv444 conversion using arm neon

---

lib/src/gainmapmath.cpp
lib/src/jpegr.cpp

During gamut conversion of linear inputs, the hdr intent pixels are getting clamped to 1.0 (diffuse white). This is fixed.

fix clamping of hdr pixels to diffuse white

---

.github/workflows/cmake_mac.yml
lib/include/ultrahdr/icc.h
lib/src/icc.cpp

color space of the image can be signalled via cicp tag in icc. While parsing for gamut space of the image, use the information present in this tag as well (if available).
Test: ./ultrahdr_app <options>

use cicp tag info if present while parsing for gamut space

---

lib/include/ultrahdr/gainmapmath.h
lib/src/gainmapmath.cpp
lib/src/jpegr.cpp
tests/gainmapmath_test.cpp

while computing gain for near blacks or pixels with channel values zero, sdr_offset is used. This value is extremely small and can result large gainmap coefficient. During encode-decode process, if this sdr pixel flips to zero, after applying gainmap the hdr pixel will blow out. It is best if the gainmap computation logic is desensitized for dark pixels.
also, conversion from wider to narrower gamut space can cause overrange values. clip only negative excursions so that domain of computeGain remains positive.
Test: ./ultrahdr_app

improve gainmap computation logic for dark pixels

---

lib/src/gainmapmath.cpp
lib/src/icc.cpp
lib/src/jpegr.cpp
tests/gainmapmath_test.cpp

- luminance function for p3 gamut is using weights of dci p3 instead of display p3. this is corrected. accordingly the gamut conversions involving display p3 are updated.
- increased precision of some constants used in csc

fix primaries used for display p3 gamut

---

fuzzer/ultrahdr_legacy_fuzzer.cpp
lib/include/ultrahdr/gainmapmath.h
lib/include/ultrahdr/icc.h
lib/src/gainmapmath.cpp
lib/src/gpu/applygainmap_gl.cpp
lib/src/icc.cpp
lib/src/jpegr.cpp
lib/src/ultrahdr_api.cpp

If sdr intent and hdr intent gamut space are not identical, it is required to send hdr intent color profile as part of gainmap image. This is addressed.
Test: ./ultrahdr_app <options>
Change-Id: I0155a1dc043f3c3e0493e04e5a6eabe160756476

signal alternate image color space in gainmap image

---

lib/include/ultrahdr/ultrahdrcommon.h
lib/src/gainmapmetadata.cpp
lib/src/gpu/applygainmap_gl.cpp
lib/src/jpegr.cpp
lib/src/jpegrutils.cpp
tests/gainmapmetadata_test.cpp
tests/jpegr_test.cpp

during generateGainMap, the color spaces of hdr intent and sdr intent are unified. if a wider gamut space is converted to narrower-gamut this may result in pixel values less than zero and/or greater than 1. choosing offsets to keep the domain of log during gainmap computation is tricky. This can be mitigated by converting narrower gamut space data to wider gamut space. This yields lesser overrange values. current change implements this.
for this to work as intended writing xmp metadata in the bitstream needs to be disabled.
Test: ./ultrahdr_app options
Change-Id: I0155a1dc043f3c3e0493e04e5a6eabe160659476

choose gainmap application space adaptively basing on input gamuts

---

Android.bp
CMakeLists.txt
docs/building.md
lib/src/jpegr.cpp
tests/gainmapmath_test.cpp

as per https://developer.android.com/media/platform/hdr-image-format implementations are expected to write both xmp and iso metadata by default.
Test: ./ultrahdr_app

enable support for xmp, iso to be build time configurable

---

lib/src/jpegr.cpp

when iso and xmp are enabled together, the size of secondary image does not include the jpeg app2 marker size.
fixes #342
Test: ./ultrahdr_app

fix secondary image size compute in dual encoding

---

CMakeLists.txt

partially fixes #345
Build: cmake -G Ninja -DCMAKE_OSX_ARCHITECTURES=arm64 ../ && ninja

add support for cross compiling on apple platforms

---

lib/include/ultrahdr/ultrahdrcommon.h

The C++ header [`<cstdint>`](https://en.cppreference.com/w/cpp/header/cstdint.html) is explicitly required to be included with GCC 15 and beyond when using [fixed width integer types](https://en.cppreference.com/w/cpp/types/integer.html).
For more details, see the guide about [porting to GCC 15](https://gcc.gnu.org/gcc-15/porting_to.html#cxx).

Add missing header for GCC 15

---

CMakeLists.txt
docs/building.md

- enable building benchmarks on windows
- enable install targets for msvc
- use policy cmp0091 new
fixes #299, fixes #364

improve cmakelists.txt for windows platforms

---

examples/ultrahdr_app.cpp

This change provides an option to print gainmap metadata without completely decoding the image.
fixes #362
Test: ./ultrahdrapp -m 1 -j out.jpeg -P

add support for probe mode
